/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package attendGo;

import javax.swing.JLabel;
import serial.SerialHandler;
import services.SerialService;
import services.LogAbsensiService;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import services.DigitalClockService;

/**
 *
 * @author ADVAN
 */
public class Tapkartu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tapkartu.class.getName());
    
    private Thread clockThread1;
    /**
     * Creates new form Tapkartu
     */
    public Tapkartu() {
        initComponents();
        thread1();
        
        // --- TAMBAHKAN BARIS INI ---
        initSerialConnection(); 
        
        // --- TAMBAHKAN BARIS INI UNTUK PEMBERSIHAN ---
        // Sangat penting untuk menghapus handler saat window ditutup 
        // agar tidak terjadi kebocoran memori (memory leak).
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                SerialService.getInstance().removeHandler(rfidHandler);
                // SerialService.getInstance().disconnect(); // Buka komentar ini jika aplikasi benar-benar keluar
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 0, 6));
        jPanel1.setForeground(new java.awt.Color(94, 0, 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(822, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Absensi AttendGo");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 288;
        gridBagConstraints.ipady = 188;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(84, 286, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 286;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 261, 31, 237);
        jPanel2.add(jTextField1, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String karyawanId = jTextField1.getText().trim();
        
        if (!karyawanId.isEmpty()) {
            try {
                // 2. Panggil service absensi
                services.LogAbsensiService absensiService = new services.LogAbsensiService();
                
                // 3. Jalankan fungsi absen menggunakan ID Karyawan
                boolean sukses = absensiService.catatAbsensiManualDenganId(karyawanId, "Hadir");
                
                if (sukses) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Absen Manual Berhasil!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    jTextField1.setText(""); // Kosongkan textfield kembali
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "ID Karyawan '" + karyawanId + "' tidak terdaftar!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses absensi: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan masukkan ID Karyawan terlebih dahulu!");
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tapkartu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void thread1() {
        DigitalClockService service = new DigitalClockService(jLabel4, "EEEE, d MMMM yyyy, HH:mm:ss");
        clockThread1 = service.getThread();
        clockThread1.setName("Thread-Jam-Kiosk2");
        clockThread1.setDaemon(true);
        clockThread1.start();
    }

    // Method untuk menghubungkan ke COM Port
    private void initSerialConnection() {
        // Bungkus proses koneksi ke dalam Thread baru agar tidak memblokir UI utama
        new Thread(() -> {
            SerialService serial = SerialService.getInstance();
            
            System.out.println("INFO: Sedang mencoba menghubungkan ke scanner...");
            boolean connected = serial.connect("COM3", 9600); 
            
            // Setelah selesai mendeteksi hardware, kembalikan respon ke UI Thread (SwingUtilities)
            SwingUtilities.invokeLater(() -> {
                if (connected) {
                    // Jika berhasil konek, daftarkan handler form ini ke service
                    serial.addHandler(rfidHandler);
                    System.out.println("Sistem siap menerima tap kartu.");
                } else {
                    // Gunakan Tapkartu.this karena posisi kode sekarang berada di dalam Lambda
                    JOptionPane.showMessageDialog(Tapkartu.this, 
                        "Gagal terhubung ke Scanner RFID. Periksa koneksi USB!", 
                        "Error Hardware", JOptionPane.ERROR_MESSAGE);
                }
            });
        }).start(); // Jalankan thread latar belakang
    }

    // Method untuk menyimpan ke database lewat Service
    private void prosesAbsensi(String rawUid) {
        try {
            LogAbsensiService absensiService = new LogAbsensiService();
            
            // Asumsi: Sementara kita set "Hadir" (Kamu bisa kembangkan logikanya nanti 
            // untuk mendeteksi Terlambat/Tepat Waktu berdasarkan jam saat ini).
            absensiService.catatAbsensiScan(rawUid, "Hadir");
            
            // Beri tahu user (opsional)
            JOptionPane.showMessageDialog(this, "Absen Berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            // Kosongkan textfield setelah 2 detik agar siap untuk orang berikutnya
            new java.util.Timer().schedule(new java.util.TimerTask() {
                @Override
                public void run() {
                    jTextField1.setText("");
                }
            }, 2000);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan absensi: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Membuat handler untuk menangkap data dari SerialService
    private SerialHandler<String> rfidHandler = new SerialHandler<String>() {
        @Override
        public void onDataReceived(String data) {
            // Karena data serial masuk lewat background thread, 
            // kita WAJIB menggunakan invokeLater agar UI Swing tidak crash/freeze.
            SwingUtilities.invokeLater(() -> {
                
                // 1. Tampilkan UID kartu di Text Field UI (opsional untuk visual)
                jTextField1.setText(data);
                
                // 2. Kirim data ke Database
                prosesAbsensi(data);
            });
        }
    };
}

