/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.Color;
import java.awt.Font;
import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import services.I18nService;

/**
 *
 * @author HP VICTUS
 */
public class setting extends javax.swing.JPanel implements I18nService.I18nChangeListener {
    public static String statusAbsen;
    public static String statusLang;
    public static Preferences prefs = Preferences.userNodeForPackage(setting.class);

    /**
     * Creates new form setting
     */
    
public setting() {
        // 1. WAJIB Paling Atas: Gambar kerangka UI-nya dulu!
        initComponents();

        // 2. Ambil data dari Preferences. 
        // Beri default String "id" secara langsung, JANGAN pakai variabel yang masih null
        statusLang = prefs.get("LANGUAGE", "id"); 

        // 3. Atur posisi visual tombol toggle sesuai data yang tersimpan
        slidingLanguageToggle2.setSelectedLanguageIndexByString(statusLang);     
        
        // 4. Set bahasa secara global di I18nService menggunakan data yang sudah pasti tidak null
        I18nService.setLocale(Locale.of(statusLang)); 
        
        // 5. Daftarkan panel ini agar mendengarkan perubahan bahasa
        I18nService.registerListener(this); 
        
        // 6. Panggil fungsi ini agar judul Border (Garis Tepi) langsung digambar saat panel dibuka
        onLanguageChanged(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        slidingLanguageToggle2 = new pallete.SlidingLanguageToggle();
        slidingStatusToggle2 = new pallete.SlidingStatusToggle();

        setBackground(new java.awt.Color(153, 0, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        slidingLanguageToggle2.setText("slidingLanguageToggle2");

        slidingStatusToggle2.setText("slidingStatusToggle2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slidingStatusToggle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slidingLanguageToggle2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(slidingLanguageToggle2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(slidingStatusToggle2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private pallete.SlidingLanguageToggle slidingLanguageToggle2;
    private pallete.SlidingStatusToggle slidingStatusToggle2;
    // End of variables declaration//GEN-END:variables

    public void onLanguageChanged() {
        SwingUtilities.invokeLater(() -> {            
       
            this.revalidate();
            this.repaint();
        });
    }
}
