/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.Color;
import java.awt.Font;
import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import services.I18nService;

/**
 *
 * @author HP VICTUS
 */
public class setting extends javax.swing.JPanel implements I18nService.I18nChangeListener {
    public static String statusAbsen;
    public static String statusLang;
    public static Preferences prefs = Preferences.userNodeForPackage(setting.class);

    /**
     * Creates new form setting
     */
    
public setting() {
        // 1. WAJIB Paling Atas: Gambar kerangka UI-nya dulu!
        initComponents();

        // 2. Ambil data dari Preferences. 
        // Beri default String "id" secara langsung, JANGAN pakai variabel yang masih null
        statusLang = prefs.get("LANGUAGE", "id"); 

        // 3. Atur posisi visual tombol toggle sesuai data yang tersimpan
        slidingLanguageToggle2.setSelectedLanguageIndexByString(statusLang);     
        
        // 4. Set bahasa secara global di I18nService menggunakan data yang sudah pasti tidak null
        I18nService.setLocale(Locale.of(statusLang)); 
        
        // 5. Daftarkan panel ini agar mendengarkan perubahan bahasa
        I18nService.registerListener(this); 
        
        // 6. Panggil fungsi ini agar judul Border (Garis Tepi) langsung digambar saat panel dibuka
        onLanguageChanged(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        slidingLanguageToggle2 = new pallete.SlidingLanguageToggle();

        setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        slidingLanguageToggle2.setText("slidingLanguageToggle2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(slidingLanguageToggle2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(slidingLanguageToggle2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 91, 48, 117);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private pallete.SlidingLanguageToggle slidingLanguageToggle2;
    // End of variables declaration//GEN-END:variables

    public void onLanguageChanged() {
        SwingUtilities.invokeLater(() -> {            
       
            this.revalidate();
            this.repaint();
        });
    }
}
